package cp.fitrie

import cp.naming.{FieldLabel, Identifier}
import cp.primitive.{BinaryOperator, PrimitiveType, PrimitiveValue}
import cp.util.Result

final case class TermVariableIndex(value: Int) {
  require(value >= 0, "a term-variable index cannot be negative")
}

final case class NodeReferenceIndex(value: Int) {
  require(value >= 0, "a node-reference index cannot be negative")
}

final case class PathVariableIndex(value: Int) {
  require(value >= 0, "a path-variable index cannot be negative")
}

final case class RecursivePathVariableIndex(value: Int) {
  require(value >= 0, "a recursive path-variable index cannot be negative")
}

enum RouteKey {
  case Application
  case TypeApplication
  case Projection(label: FieldLabel)
  case Unfold

  def rootKey: RootKey = RootKey.Route(this)

  private[fitrie] def introducedTermVariables: Int = this match {
    case Application => 1
    case TypeApplication | Projection(_) | Unfold => 0
  }

  private[fitrie] def introducedPathVariables: Int = this match {
    case TypeApplication => 1
    case Application | Projection(_) | Unfold => 0
  }
}

enum RootKey {
  case Route(routeKey: RouteKey)
  case Termination(primitiveType: PrimitiveType)
}

/**
 * The executable key-label fragment generated by Fiobs types. It represents
 * finite and cofinite root-key sets, including the complete key universe used
 * for bottom.
 */
enum RootKeySet {
  case Universal
  case Finite(rootKeys: Set[RootKey])
  case Cofinite(excludedRootKeys: Set[RootKey])

  def contains(rootKey: RootKey): Boolean = this match {
    case Universal => true
    case Finite(rootKeys) => rootKeys.contains(rootKey)
    case Cofinite(excludedRootKeys) => !excludedRootKeys.contains(rootKey)
  }

  def union(other: RootKeySet): RootKeySet = (this, other) match {
    case (Universal, _) | (_, Universal) => Universal
    case (Finite(leftKeys), Finite(rightKeys)) => Finite(leftKeys ++ rightKeys)
    case (Finite(finiteKeys), Cofinite(excludedKeys)) =>
      RootKeySet.cofinite(excludedKeys -- finiteKeys)
    case (Cofinite(excludedKeys), Finite(finiteKeys)) =>
      RootKeySet.cofinite(excludedKeys -- finiteKeys)
    case (Cofinite(leftExcluded), Cofinite(rightExcluded)) =>
      RootKeySet.cofinite(leftExcluded.intersect(rightExcluded))
  }

  def intersection(other: RootKeySet): RootKeySet = (this, other) match {
    case (Universal, rootKeys) => rootKeys
    case (rootKeys, Universal) => rootKeys
    case (Finite(leftKeys), Finite(rightKeys)) => Finite(leftKeys.intersect(rightKeys))
    case (Finite(finiteKeys), Cofinite(excludedKeys)) => Finite(finiteKeys -- excludedKeys)
    case (Cofinite(excludedKeys), Finite(finiteKeys)) => Finite(finiteKeys -- excludedKeys)
    case (Cofinite(leftExcluded), Cofinite(rightExcluded)) =>
      RootKeySet.cofinite(leftExcluded ++ rightExcluded)
  }

  def difference(other: RootKeySet): RootKeySet = intersection(other.complement)

  def isDisjointFrom(other: RootKeySet): Boolean = intersection(other).isEmpty

  def isEmpty: Boolean = this match {
    case Universal | Cofinite(_) => false
    case Finite(rootKeys) => rootKeys.isEmpty
  }

  private def complement: RootKeySet = this match {
    case Universal => Finite(Set.empty)
    case Finite(rootKeys) => RootKeySet.cofinite(rootKeys)
    case Cofinite(excludedRootKeys) => Finite(excludedRootKeys)
  }
}

object RootKeySet {
  val empty: RootKeySet = RootKeySet.Finite(Set.empty)

  def one(rootKey: RootKey): RootKeySet = RootKeySet.Finite(Set(rootKey))

  private[fitrie] def cofinite(excludedRootKeys: Set[RootKey]): RootKeySet = {
    if (excludedRootKeys.isEmpty) RootKeySet.Universal
    else RootKeySet.Cofinite(excludedRootKeys)
  }
}

enum Request {
  case Application(argument: FiTrie)
  case TypeApplication(pathInterface: ObservationPathInterface)
  case Projection(label: FieldLabel)
  case Unfold

  def routeKey: RouteKey = this match {
    case Application(_) => RouteKey.Application
    case TypeApplication(_) => RouteKey.TypeApplication
    case Projection(label) => RouteKey.Projection(label)
    case Unfold => RouteKey.Unfold
  }
}

final case class RequestSet(requests: Set[Request]) {
  def isEmpty: Boolean = requests.isEmpty
}

object RequestSet {
  val empty: RequestSet = RequestSet(Set.empty)

  def one(request: Request): RequestSet = RequestSet(Set(request))
}

/** A finite dependent map from primitive termination keys to matching payloads. */
final case class TerminationPayloads private (entries: Map[PrimitiveType, PrimitiveValue]) {
  require(
    entries.forall { case (primitiveType, payload) => payload.primitiveType == primitiveType },
    "every termination payload must match its primitive termination key"
  )

  def get(primitiveType: PrimitiveType): Option[PrimitiveValue] = entries.get(primitiveType)

  def contains(primitiveType: PrimitiveType): Boolean = entries.contains(primitiveType)

  def isEmpty: Boolean = entries.isEmpty

  private[fitrie] def restrict(selectedRootKeys: RootKeySet): TerminationPayloads = {
    TerminationPayloads.fromEntries(entries.filter { case (primitiveType, _) =>
      selectedRootKeys.contains(RootKey.Termination(primitiveType))
    })
  }
}

object TerminationPayloads {
  val empty: TerminationPayloads = new TerminationPayloads(Map.empty)

  def one(payload: PrimitiveValue): TerminationPayloads = {
    new TerminationPayloads(Map(payload.primitiveType -> payload))
  }

  private[fitrie] def fromEntries(
    entries: Map[PrimitiveType, PrimitiveValue]
  ): TerminationPayloads = new TerminationPayloads(entries)
}

enum ResponseComputation {
  case LocalVariable(index: TermVariableIndex)
  case Global(identifier: Identifier)
  case StructuralReference(index: NodeReferenceIndex)
  case Index(receiver: FiTrie, requests: RequestSet)
  case Filter(receiver: FiTrie, selectedRootKeys: RootKeyExpression)

  /** Calculus-specific primitive response corresponding to the universal ξ form. */
  case PrimitiveOperation(operator: BinaryOperator, left: FiTrie, right: FiTrie)

  /** Calculus-specific lazy conditional response corresponding to the universal ξ form. */
  case Conditional(condition: FiTrie, whenTrue: FiTrie, whenFalse: FiTrie)
}

final case class FiTrie private (
  responseComputations: Set[ResponseComputation],
  routeContinuations: Map[RouteKey, FiTrie],
  terminationPayloads: TerminationPayloads
) {
  override def toString: String = FiTrieRendering.render(this)

  def filter(selectedRootKeys: RootKeySet): FiTrie = FiTrieAlgebra.filter(this, selectedRootKeys)

  /**
   * Computes one request residual in the current structural scope. A selected
   * continuation retains the receiver root as an ambient node binder, so a
   * residual of a recursive trie need not be closed when viewed in isolation.
   * Closed execution goes through [[cp.fitrie.evaluation.Evaluation]], which
   * preserves those binder edges before indexing.
   */
  def index(requests: RequestSet): Result[FiTrie, FiTrieMergeError] = {
    FiTrieAlgebra.index(this, requests)
  }

  def shiftTermVariables(by: Int, cutoff: Int = 0): FiTrie = {
    FiTrieBinding.shiftTermVariables(this, by, cutoff)
  }

  def shiftNodeReferences(by: Int, cutoff: Int = 0): FiTrie = {
    FiTrieBinding.shiftNodeReferences(this, by, cutoff)
  }

  def shiftPathVariables(by: Int, cutoff: Int = 0): FiTrie = {
    FiTrieBinding.shiftPathVariables(this, by, cutoff)
  }

  def substituteTermVariable(
    index: TermVariableIndex,
    replacement: FiTrie
  ): Result[FiTrie, FiTrieMergeError] = {
    FiTrieBinding.substituteTermVariable(this, index, replacement)
  }

  def substitutePathVariable(
    index: PathVariableIndex,
    replacement: ObservationPathInterface
  ): FiTrie = {
    FiTrieBinding.substitutePathVariable(this, index, replacement)
  }

  def tieFixedPoint(
    index: TermVariableIndex,
    selectedRootKeys: RootKeyExpression
  ): FiTrie = {
    FiTrieBinding.tieFixedPoint(this, index, selectedRootKeys)
  }

  def isWellScoped(
    termVariableDepth: Int = 0,
    nodeReferenceDepth: Int = 0,
    pathVariableDepth: Int = 0
  ): Boolean = {
    require(termVariableDepth >= 0, "the term-variable scope depth cannot be negative")
    require(nodeReferenceDepth >= 0, "the node-reference scope depth cannot be negative")
    require(pathVariableDepth >= 0, "the path-variable scope depth cannot be negative")
    FiTrieBinding.isWellScoped(this, termVariableDepth, nodeReferenceDepth, pathVariableDepth)
  }
}

object FiTrie {
  val empty: FiTrie = new FiTrie(Set.empty, Map.empty, TerminationPayloads.empty)

  def node(
    responseComputations: Set[ResponseComputation] = Set.empty,
    routeContinuations: Map[RouteKey, FiTrie] = Map.empty,
    terminationPayloads: TerminationPayloads = TerminationPayloads.empty
  ): FiTrie = new FiTrie(responseComputations, routeContinuations, terminationPayloads)

  def response(responseComputation: ResponseComputation): FiTrie = {
    node(responseComputations = Set(responseComputation))
  }

  def termination(payload: PrimitiveValue): FiTrie = {
    node(terminationPayloads = TerminationPayloads.one(payload))
  }

  def route(routeKey: RouteKey, continuation: FiTrie): FiTrie = {
    node(routeContinuations = Map(routeKey -> continuation))
  }

  def merge(left: FiTrie, right: FiTrie): Result[FiTrie, FiTrieMergeError] = {
    FiTrieAlgebra.merge(left, right)
  }

  def mergeAll(tries: IterableOnce[FiTrie]): Result[FiTrie, FiTrieMergeError] = {
    FiTrieAlgebra.mergeAll(tries)
  }
}
